### ISSUE TITLE
[Bug] No pull request created after clicking on using the template

### ISSUE THREAD

**Issue by juanpflores** [skills/resolve-merge-conflicts#7]
**Describe the bug**
Right after using the template repository, GitHub Actions fail to create the pull request to start the lesson.

**To Reproduce**
1. Click on "Use this template"
2. Create a private repository
3. When the repository is initialized, you'll get an error during the initialization of the repository.

**Expected behavior**
Right after creating the new repository, there is a GitHub Action that creates a pull request to simulate a merge conflict. 

**Screenshots**
![image](https://user-images.githubusercontent.com/6200135/211862938-d34aa727-921b-410e-b74e-fb8b6f2f7cb0.png)

```
Make a pull request
Warning: 1 uncommitted change
pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)
Error: Process completed with exit code 1.
```

**Device information**
 - Type: MacBook Pro
 - OS: iOS
 - Browser: Chrome 
 - Version: Version 109.0.5414.87 (Official Build) (arm64)

**Additional context**
❤️

**Comment by r28yao** [comment]
Thank you! I am experiencing the same situation

**Comment by swapnilbawane** [comment]
Thank you. I am unable to follow the further lessons because of this issue. Hope this is resolved.

**Comment by JChap13** [comment]
from what (little) i understand it seems like theyre updating something major which screws with the tutorials

For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

**Comment by marcosolina** [comment]
Similar issue here. I have simply clicked on the "use this template button" as suggested in the readme file and then I get the error below. Any updates?

![image](https://user-images.githubusercontent.com/26163844/216957648-e0495705-17d8-4958-912e-bb6f67b26344.png)

**Comment by sinsukehlab** [comment]
The error exit code 1 occurred because GitHub Actions are not permitted to create pull requests. You should manage the **Allow GitHub Actions to create and approve pull requests** setting in organization settings under Actions > General > Workflow permissions.

https://github.blog/changelog/2022-05-03-github-actions-prevent-github-actions-from-creating-and-approving-pull-requests/

There should be a warning that says Node.js 12 actions are deprecated. This occurred because the actions use actions/checkout@v2. I will open a PR to bump it to v3. For now, replace all "actions/checkout@v2" to "actions/checkout@v3" and the warning will be fixed.

**Comment by sinsukehlab** [comment]
The workflow `0-start.yml` in the course skills/release-based-workflow also creates a pull request but it runs without errors. The restriction can probably be circumvented by running shell scripts (`.github/script/*.sh`) instead of running commands directly coded in YAML files (`.github/workflows/*.yml`).

**Comment by dankatri** [comment]
+1 to this, I'm getting the same error in the action:

`pull request create failed: GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)`
